services:

    LSB\OrderBundle\Form\OrderType:
        tags:
            - name: form.type

    LSB\OrderBundle\Form\OrderPackageType:
        tags:
            - name: form.type

    LSB\OrderBundle\Form\OrderPackageItemType:
        tags:
            - name: form.type

    LSB\OrderBundle\Form\OrderNoteType:
        tags:
            - name: form.type

    LSB\OrderBundle\Form\CartType:
        tags:
            - name: form.type

    LSB\OrderBundle\Form\CartItemType:
        tags:
            - name: form.type

    LSB\OrderBundle\Form\CartPackageItemType:
        tags:
            - name: form.type

    LSB\OrderBundle\Form\CartPackageType:
        tags:
            - name: form.type

    ### Package Shipping
    LSB\OrderBundle\Form\CartModule\PackageShipping\CartPackageShippingType:
        arguments:
            - '@LSB\OrderBundle\Manager\CartPackageManager'
        tags:
            - name: form.type

    LSB\OrderBundle\Form\CartModule\PackageShipping\CartPackagesType:
        arguments:
            - '@LSB\OrderBundle\Manager\CartManager'
        tags:
            - name: form.type

    ### Payment
    LSB\OrderBundle\Form\CartModule\Payment\PaymentType:
        arguments:
            - '@LSB\OrderBundle\Manager\CartManager'
        tags:
            -   name: form.type