services:

    LSB\OrderBundle\Form\OrderType:
        tags:
            -
                name: form.type

    LSB\OrderBundle\Form\OrderPackageType:
        tags:
            -
                name: form.type

    LSB\OrderBundle\Form\OrderPackageItemType:
        tags:
            -
                name: form.type

    LSB\OrderBundle\Form\OrderNoteType:
        tags:
            -
                name: form.type
        #   FIXME: Poprawna forma zapisu:
        #  - {name: form.type}
        #   FIXME: Poprawna forma zapisu:
        #  - {name: form.type}
        #   FIXME: Poprawna forma zapisu:
        #  - {name: form.type}
        #   FIXME: Poprawna forma zapisu:
        #  - {name: form.type}