services:
    LSB\OrderBundle\Manager\OrderManager:
        arguments:
            - '@lsb_utility_object_manager'

    LSB\OrderBundle\Manager\OrderPackageManager:
        arguments:
            - '@lsb_utility_object_manager'

    LSB\OrderBundle\Manager\OrderPackageItemManager:
        arguments:
            - '@lsb_utility_object_manager'

    LSB\OrderBundle\Manager\OrderNoteManager:
        arguments:
            - '@lsb_utility_object_manager'

    LSB\OrderBundle\Manager\CartManager:
        arguments:
            - '@lsb_utility_object_manager'

    LSB\OrderBundle\Manager\CartItemManager:
        arguments:
            - '@lsb_utility_object_manager'

    LSB\OrderBundle\Manager\CartPackageItemManager:
        arguments:
            - '@lsb_utility_object_manager'

    LSB\OrderBundle\Manager\CartPackageManager:
        arguments:
            - '@lsb_utility_object_manager'