parameters:
    choice_list.cart.auth:
services:
    LSB\OrderBundle\Calculator\OrderTotalCalculator:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '@security.token_storage'
        tags:
            - { name: calculator.total }

    LSB\OrderBundle\Calculator\OrderPackageTotalCalculator:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '@security.token_storage'
        tags:
            - { name: calculator.total }