parameters:
    choice_list.cart.auth:
services:
    LSB\OrderBundle\Service\CartConverterService: ~

    ### Generator services
    LSB\OrderBundle\Service\CartStepGeneratorService:
        arguments:
            - '@LSB\OrderBundle\Service\CartStepGeneratorInventory'

    LSB\OrderBundle\Service\CartStepGeneratorInventory: ~

    LSB\OrderBundle\CartGenerator\CartStep1Generator:
        tags: [ { name: cart.step.generator, step: 1 } ]
        arguments:
            - '@LSB\OrderBundle\Service\CartModuleService'
            - '@LSB\OrderBundle\Service\CartService'
            - '@doctrine.orm.entity_manager'
            - '@LSB\OrderBundle\Service\CartConverterService'
            - '@request_stack'
            - '@event_dispatcher'

    LSB\OrderBundle\Calculator\OrderTotalCalculator:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '@security.token_storage'
        tags:
            - { name: calculator.total }

    LSB\OrderBundle\Calculator\OrderPackageTotalCalculator:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '@security.token_storage'
        tags:
            - { name: calculator.total }

    LSB\OrderBundle\Calculator\CartTotalCalculator:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '@security.token_storage'
            - '@parameter_bag'
            - '@LSB\OrderBundle\Service\CartCalculatorService'
            - '@LSB\OrderBundle\CartComponent\DataCartComponent'
            - '@LSB\PricelistBundle\Manager\PricelistManager'
            - '@LSB\OrderBundle\Service\CartModuleService'
        tags:
            - { name: calculator.total }

    LSB\OrderBundle\Service\CartService:
        arguments:
            - '@LSB\OrderBundle\Manager\CartManager'
            - '@doctrine.orm.entity_manager'
            - '@translator'
            - '@security.token_storage'
            - '@parameter_bag'
            - '@LSB\ProductBundle\Manager\ProductManager'
            - '@LSB\ProductBundle\Manager\StorageManager'
            - '@LSB\PricelistBundle\Manager\PricelistManager'
            - '@LSB\LocaleBundle\Manager\TaxManager'
            - '@LSB\OrderBundle\Service\CartModuleService'
            - '@event_dispatcher'
            - '@request_stack'
            - '@LSB\OrderBundle\Service\CartComponentService'

    LSB\OrderBundle\Service\CartModuleService:
        lazy: true
        arguments:
            - '@LSB\OrderBundle\Service\CartModuleInventory'
            - '@parameter_bag'
            - '@doctrine.orm.entity_manager'
            - '@translator'
            - '@LSB\OrderBundle\Service\CartService'
            - '@LSB\PricelistBundle\Manager\PricelistManager'
            - '@event_dispatcher'
            - '@security.token_storage'
            - '@LSB\ProductBundle\Manager\ProductManager'
            - '@LSB\LocaleBundle\Manager\TaxManager'
            - '@LSB\PricelistBundle\Manager\PricelistManager'
            - '@LSB\ProductBundle\Manager\StorageManager'
            - '@form.factory'
            - '@jms_serializer.serializer'
            - '@LSB\UserBundle\Manager\UserManager'
            - '@validator'
            - '@router.default'
            - '@LSB\OrderBundle\Service\CartCalculatorService'
            - '@security.authorization_checker'
            - '@LSB\OrderBundle\Service\CartStepGeneratorService'
            - '@twig'
            - '@LSB\OrderBundle\Service\CartComponentService'

    LSB\OrderBundle\Service\CartCalculatorService:
        lazy: true
        arguments:
            - '@parameter_bag'
            - '@doctrine.orm.entity_manager'
            - '@translator'
            - '@event_dispatcher'
            - '@security.token_storage'
            - '@LSB\LocaleBundle\Manager\TaxManager'
            - '@LSB\PricelistBundle\Manager\PricelistManager'
            - '@request_stack'
            - '@jms_serializer.serializer'
            - '@LSB\OrderBundle\Service\CartCalculatorInventory'


    LSB\OrderBundle\Service\CartComponentService:
        arguments:
            - '@LSB\OrderBundle\Service\CartComponentInventory'

    LSB\OrderBundle\Service\CartModuleInventory: ~

    LSB\OrderBundle\Service\CartComponentInventory: ~

    LSB\OrderBundle\Service\CartCalculatorInventory: ~

    #modules
    LSB\OrderBundle\CartModule\DataCartModule:
        arguments:
            - '@LSB\OrderBundle\CartComponent\DataCartComponent'
        tags:
            -   name: cart.module

    LSB\OrderBundle\CartModule\CartItemCartModule:
        arguments:
            - '@LSB\OrderBundle\CartComponent\DataCartComponent'
            - '@LSB\OrderBundle\CartComponent\CartItemCartComponent'
        tags:
            -   name: cart.module

    LSB\OrderBundle\CartModule\PackageSplitCartModule:
        arguments:
            - '@LSB\OrderBundle\CartComponent\DataCartComponent'
            - '@LSB\OrderBundle\CartComponent\PackageSplitCartComponent'
            - '@LSB\OrderBundle\CartComponent\CartItemCartComponent'
        tags:
            -   name: cart.module

    LSB\OrderBundle\CartModule\PackageShippingCartModule:
        arguments:
            - '@LSB\OrderBundle\CartComponent\DataCartComponent'
            - '@LSB\OrderBundle\CartComponent\PackageShippingCartComponent'
            - '@LSB\OrderBundle\CartComponent\CartItemCartComponent'
        tags:
            -   name: cart.module

    LSB\OrderBundle\CartModule\PaymentCartModule:
        arguments:
            - '@LSB\OrderBundle\CartComponent\DataCartComponent'
            - '@LSB\OrderBundle\CartComponent\PaymentCartComponent'
        tags:
            -   name: cart.module

    #components
    LSB\OrderBundle\CartComponent\DataCartComponent:
        arguments:
            - '@security.token_storage'
            - '@parameter_bag'
            - '@LSB\OrderBundle\Manager\CartManager'
            - '@LSB\OrderBundle\Manager\CartItemManager'
            - '@LSB\ShippingBundle\Manager\MethodManager'
            - '@LSB\PricelistBundle\Manager\PricelistManager'
            - '@LSB\ProductBundle\Manager\StorageManager'
            - '@LSB\ProductBundle\Service\StorageService'
            - '@request_stack'
            - '@event_dispatcher'
            - '@LSB\LocaleBundle\Manager\TaxManager'
            - '@form.factory'
            - '@LSB\UserBundle\Manager\UserManager'
            - '@jms_serializer.serializer'
            - '@security.authorization_checker'
            - '@twig'
            - '@translator'
            - '@LSB\ProductBundle\Manager\ProductManager'
            - '@LSB\ProductBundle\Manager\ProductSetProductManager'
            - '@LSB\OrderBundle\Service\CartCalculatorService'
            - '@LSB\PricelistBundle\Service\TotalCalculatorManager'
        tags:
            -   name: cart.component


    LSB\OrderBundle\CartComponent\CartItemCartComponent:
        arguments:
            - '@security.token_storage'
            - '@LSB\ProductBundle\Manager\ProductManager'
            - '@LSB\OrderBundle\Manager\CartManager'
            - '@LSB\OrderBundle\Manager\CartItemManager'
            - '@parameter_bag'
            - '@LSB\PricelistBundle\Manager\PricelistManager'
            - '@translator'
            - '@LSB\ProductBundle\Manager\StorageManager'
            - '@LSB\ProductBundle\Service\StorageService'
        tags:
            -   name: cart.component


    LSB\OrderBundle\CartComponent\PackageSplitCartComponent:
        arguments:
            - '@security.token_storage'
            - '@LSB\OrderBundle\Manager\CartManager'
            - '@LSB\OrderBundle\Manager\CartPackageManager'
            - '@LSB\ProductBundle\Manager\SupplierManager'
            - '@LSB\OrderBundle\Manager\CartPackageItemManager'
            - '@LSB\ProductBundle\Service\StorageService'
            - '@parameter_bag'
        tags:
            -   name: cart.component

    LSB\OrderBundle\CartComponent\PackageShippingCartComponent:
        arguments:
            - '@security.token_storage'
            - '@LSB\OrderBundle\Manager\CartPackageManager'
            - '@LSB\ProductBundle\Manager\SupplierManager'
            - '@LSB\OrderBundle\Manager\CartPackageItemManager'
            - '@LSB\ProductBundle\Service\StorageService'
            - '@LSB\ShippingBundle\Manager\MethodManager'
            - '@LSB\OrderBundle\Service\CartCalculatorService'
        tags:
            -   name: cart.component

    LSB\OrderBundle\CartComponent\PaymentCartComponent:
        arguments:
            - '@security.token_storage'
            - '@LSB\PaymentBundle\Manager\MethodManager'
            - '@LSB\OrderBundle\Service\CartCalculatorService'
            - '@LSB\OrderBundle\Manager\CartManager'
        tags:
            -   name: cart.component

    LSB\OrderBundle\Calculator\DefaultShippingMethodCalculator:
        tags: [ { name: cart.calculator } ]

    LSB\OrderBundle\Calculator\DefaultPaymentMethodCalculator:
        tags: [ { name: cart.calculator } ]

    LSB\OrderBundle\Calculator\DefaultDataCartCalculator:
        tags: [ { name: cart.calculator } ]
        arguments:
            - '@parameter_bag'
            - '@LSB\OrderBundle\CartComponent\DataCartComponent'
            - '@LSB\PricelistBundle\Manager\PricelistManager'